# 版本
version: '0.0.1'

# DB
database:
  type: 'mysql'
  host: '127.0.0.1'
  port: '3306'
  dbname: 'test'
  user: 'root'
  password: 'root'
  charset: 'utf8'
  prefix: ''

# redis
redis:
  host: '127.0.0.1'
  port: '6379'
  password: ~
  select: 0
  prefix: ''
