# 版本
version: '0.0.7'

# DB
database:
  enable: true
  type: 'mysql'
  host: '127.0.0.1'
  port: '3306'
  dbname: 'test'
  user: 'root'
  password: 'root'
  charset: 'utf8'
  prefix: ''

# redis
redis:
  enable: true
  host: '127.0.0.1'
  port: '6379'
  password: ~
  select: 0
  prefix: ''

# log
logs:
  log_max_files: 10

# lang
lang: 'zh-CN'

# twig
twig:
  view_suffix: '.html'
  cache_dir: 'volt'